import { useState } from "react";

import Head from "../components/pages/students/Head";
import Filter from "../components/pages/students/Filter";
import Grid from "../components/pages/students/grid/Grid";

import Divider from "../components/utils/Divider";
import Spacer from "../components/utils/Spacer";


const studentsData = [
  {
    id: 1,
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    name: "John Doe",
    courseCompletion: 95,
    feeStatus: "deposited",
    courseDuration: "6 Months",
    classesAttend: 20,
  },
  {
    id: 2,
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    name: "Emily Smith",
    courseCompletion: 80,
    feeStatus: "pending",
    courseDuration: "1 Year",
    classesAttend: 150,
  },
  {
    id: 3,
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
    name: "James Johnson",
    courseCompletion: 70,
    feeStatus: "deposited",
    courseDuration: "3 Months",
    classesAttend: 10,
  },
  {
    id: 4,
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
    name: "Sarah Brown",
    courseCompletion: 60,
    feeStatus: "pending",
    courseDuration: "2 Years",
    classesAttend: 200,
  },
  {
    id: 5,
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
    name: "David Davis",
    courseCompletion: 85,
    feeStatus: "deposited",
    courseDuration: "1 Year",
    classesAttend: 100,
  },
  {
    id: 6,
    avatar: "https://randomuser.me/api/portraits/women/6.jpg",
    name: "Linda Wilson",
    courseCompletion: 75,
    feeStatus: "pending",
    courseDuration: "6 Months",
    classesAttend: 25,
  },
  {
    id: 7,
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
    name: "Charles Moore",
    courseCompletion: 90,
    feeStatus: "deposited",
    courseDuration: "4 Months",
    classesAttend: 15,
  },
  {
    id: 8,
    avatar: "https://randomuser.me/api/portraits/women/8.jpg",
    name: "Olivia Taylor",
    courseCompletion: 65,
    feeStatus: "pending",
    courseDuration: "2 Years",
    classesAttend: 250,
  },
  {
    id: 9,
    avatar: "https://randomuser.me/api/portraits/men/9.jpg",
    name: "Thomas Anderson",
    courseCompletion: 50,
    feeStatus: "deposited",
    courseDuration: "8 Months",
    classesAttend: 30,
  },
  {
    id: 10,
    avatar: "https://randomuser.me/api/portraits/women/10.jpg",
    name: "Isabella Thomas",
    courseCompletion: 80,
    feeStatus: "pending",
    courseDuration: "1 Year",
    classesAttend: 120,
  },
  {
    id: 11,
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
    name: "Matthew Jackson",
    courseCompletion: 55,
    feeStatus: "deposited",
    courseDuration: "9 Months",
    classesAttend: 28,
  },
  {
    id: 12,
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
    name: "Sophia White",
    courseCompletion: 85,
    feeStatus: "pending",
    courseDuration: "6 Months",
    classesAttend: 22,
  },
  {
    id: 13,
    avatar: "https://randomuser.me/api/portraits/men/13.jpg",
    name: "Mark Harris",
    courseCompletion: 70,
    feeStatus: "deposited",
    courseDuration: "1 Year",
    classesAttend: 110,
  },
  {
    id: 14,
    avatar: "https://randomuser.me/api/portraits/women/14.jpg",
    name: "Emma Martin",
    courseCompletion: 95,
    feeStatus: "pending",
    courseDuration: "3 Months",
    classesAttend: 8,
  },
  {
    id: 15,
    avatar: "https://randomuser.me/api/portraits/men/15.jpg",
    name: "Joshua Thompson",
    courseCompletion: 60,
    feeStatus: "deposited",
    courseDuration: "2 Years",
    classesAttend: 180,
  },
  {
    id: 16,
    avatar: "https://randomuser.me/api/portraits/women/16.jpg",
    name: "Ava Garcia",
    courseCompletion: 75,
    feeStatus: "pending",
    courseDuration: "6 Months",
    classesAttend: 20,
  },
  {
    id: 17,
    avatar: "https://randomuser.me/api/portraits/men/17.jpg",
    name: "Ethan Martinez",
    courseCompletion: 85,
    feeStatus: "deposited",
    courseDuration: "1 Year",
    classesAttend: 135,
  },
  {
    id: 18,
    avatar: "https://randomuser.me/api/portraits/women/18.jpg",
    name: "Mia Robinson",
    courseCompletion: 50,
    feeStatus: "pending",
    courseDuration: "4 Months",
    classesAttend: 12,
  },
  {
    id: 19,
    avatar: "https://randomuser.me/api/portraits/men/19.jpg",
    name: "Nicholas Clark",
    courseCompletion: 65,
    feeStatus: "deposited",
    courseDuration: "2 Years",
    classesAttend: 220,
  },
  {
    id: 20,
    avatar: "https://randomuser.me/api/portraits/women/20.jpg",
    name: "Lily Rodriguez",
    courseCompletion: 90,
    feeStatus: "pending",
    courseDuration: "1 Year",
    classesAttend: 140,
  },
  {
    id: 21,
    avatar: "https://randomuser.me/api/portraits/men/21.jpg",
    name: "James Lewis",
    courseCompletion: 55,
    feeStatus: "deposited",
    courseDuration: "6 Months",
    classesAttend: 25,
  },
  {
    id: 22,
    avatar: "https://randomuser.me/api/portraits/women/22.jpg",
    name: "Avery Walker",
    courseCompletion: 70,
    feeStatus: "pending",
    courseDuration: "3 Months",
    classesAttend: 14,
  },
  {
    id: 23,
    avatar: "https://randomuser.me/api/portraits/men/23.jpg",
    name: "Benjamin Hall",
    courseCompletion: 80,
    feeStatus: "deposited",
    courseDuration: "1 Year",
    classesAttend: 95,
  },
  {
    id: 24,
    avatar: "https://randomuser.me/api/portraits/women/24.jpg",
    name: "Chloe Allen",
    courseCompletion: 90,
    feeStatus: "pending",
    courseDuration: "8 Months",
    classesAttend: 32,
  },
  {
    id: 25,
    avatar: "https://randomuser.me/api/portraits/men/25.jpg",
    name: "Mason Young",
    courseCompletion: 65,
    feeStatus: "deposited",
    courseDuration: "2 Years",
    classesAttend: 200,
  },
  {
    id: 26,
    avatar: "https://randomuser.me/api/portraits/women/26.jpg",
    name: "Ella Hernandez",
    courseCompletion: 75,
    feeStatus: "pending",
    courseDuration: "1 Year",
    classesAttend: 120,
  },
  {
    id: 27,
    avatar: "https://randomuser.me/api/portraits/men/27.jpg",
    name: "Oliver King",
    courseCompletion: 50,
    feeStatus: "deposited",
    courseDuration: "4 Months",
    classesAttend: 18,
  },
  {
    id: 28,
    avatar: "https://randomuser.me/api/portraits/women/28.jpg",
    name: "Henry Wright",
    courseCompletion: 85,
    feeStatus: "pending",
    courseDuration: "2 Years",
    classesAttend: 230,
  },
  {
    id: 29,
    avatar: "https://randomuser.me/api/portraits/men/29.jpg",
    name: "Alexander Scott",
    courseCompletion: 60,
    feeStatus: "deposited",
    courseDuration: "6 Months",
    classesAttend: 14,
  },
  {
    id: 30,
    avatar: "https://randomuser.me/api/portraits/women/30.jpg",
    name: "Grace White",
    courseCompletion: 90,
    feeStatus: "pending",
    courseDuration: "1 Year",
    classesAttend: 150,
  },
];


export default function Students() {

  const [students, setStudents] = useState(studentsData);

  return (
    <div className="students-page">
      <Head totalStudents={studentsData.length}/>
      <Divider className="px-5 my-5 md:px-10"/>
      <Filter originalStudents={studentsData} students={students} setStudents={setStudents}/>
      <Divider className="px-5 my-5"/>
      <Grid students={students}/>
    </div>
  );
}
